In [10]:
import pandas as pd
import numpy as np

In [14]:
a=np.array([1,2,5,3,5])
a

array([1, 2, 5, 3, 5])

In [15]:
a[2]

5

In [16]:
a=np.array([[1,2,5],[5,7,9],[5,21,7]])
a

array([[ 1,  2,  5],
       [ 5,  7,  9],
       [ 5, 21,  7]])

In [17]:
a[1]

array([5, 7, 9])

In [18]:
#ndim shows two dimentional array

a.ndim

2

In [19]:
a.itemsize

4

In [20]:
a.dtype

dtype('int32')

In [27]:
a=np.array([[1,2],[5,7],[5,21]], dtype=np.float64)
a

array([[ 1.,  2.],
       [ 5.,  7.],
       [ 5., 21.]])

In [28]:
a.dtype

dtype('float64')

In [29]:
# total number of elements
a.size

6

In [30]:
a

array([[ 1.,  2.],
       [ 5.,  7.],
       [ 5., 21.]])

In [31]:
a.shape

(3, 2)

In [26]:
a=np.array([[1,2,5],[5,7,9],[5,21,7]], dtype=complex)
a

array([[ 1.+0.j,  2.+0.j,  5.+0.j],
       [ 5.+0.j,  7.+0.j,  9.+0.j],
       [ 5.+0.j, 21.+0.j,  7.+0.j]])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
l=range(5)
l

range(0, 5)

In [36]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [37]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [44]:
np.linspace(1,20,30)

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [46]:
a

array([[ 1.,  2.],
       [ 5.,  7.],
       [ 5., 21.]])

In [47]:
a.shape

(3, 2)

In [49]:
a.reshape(2,3)

array([[ 1.,  2.,  5.],
       [ 7.,  5., 21.]])

In [52]:
a.reshape(6,1)

array([[ 1.],
       [ 2.],
       [ 5.],
       [ 7.],
       [ 5.],
       [21.]])

In [55]:
# ravel function aarange the aaray in a line
a.ravel()

array([ 1.,  2.,  5.,  7.,  5., 21.])

In [56]:
a

array([[ 1.,  2.],
       [ 5.,  7.],
       [ 5., 21.]])

In [57]:
a.min()

1.0

In [58]:
a.max()

21.0

In [59]:
a.sum()

41.0

In [60]:
a

array([[ 1.,  2.],
       [ 5.,  7.],
       [ 5., 21.]])

In [61]:
# axis=0 is for colomn

a.sum(axis=0)

array([11., 30.])

In [62]:
# axis=0 is for rows

a.sum(axis=1)

array([ 3., 12., 26.])

In [63]:
a

array([[ 1.,  2.],
       [ 5.,  7.],
       [ 5., 21.]])

In [64]:
# for square root

np.sqrt(a)

array([[1.        , 1.41421356],
       [2.23606798, 2.64575131],
       [2.23606798, 4.58257569]])

In [65]:
# for standard deviation
np.std(a)

6.64371047599825

In [66]:
a=np.array([[1,2],[5,6],[9,10]])
b=np.array([[4,5],[5,6],[4,9]])


In [67]:
a

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [68]:
b

array([[4, 5],
       [5, 6],
       [4, 9]])

In [69]:
a+b

array([[ 5,  7],
       [10, 12],
       [13, 19]])

In [70]:
a*b

array([[ 4, 10],
       [25, 36],
       [36, 90]])

In [71]:
a/b

array([[0.25      , 0.4       ],
       [1.        , 1.        ],
       [2.25      , 1.11111111]])